name: @BrunoJabs
description: Coder Thoughts
meta_description: "Pensamentos a respeito do mundo de software"

markdown: redcarpet
highlighter: pygments
logo: true
paginate: 15
baseurl: /
domain_name: 'http://brunojabs.github.io'

# Details for the RSS feed generator
url:            'http://brunojabs.github.io'
author:         'Bruno Gomes'
